### ISSUE TITLE
full version (32.2 GB)

### ISSUE THREAD

**Issue by Noname400** [bernardladenthin/BitcoinAddressFinder#11]
Good afternoon. May I ask you to post the full version (32.2 GB), last update: Feb 10, 2021
pls.. http://blockdata.loyce.club/alladdresses/ - NOT WORK

**Comment by bernardladenthin** [comment]
Hi,

the full version is already online. Have a look at http://ladenthin.net/lmdb_full.zip
The lmdb can be exported to txt using the BitcoinAddressFinder.

Greetings, Bernard

**Comment by Noname400** [comment]
E5504

**Comment by Noname400** [comment]
Tell me how to do this?

**Comment by bernardladenthin** [comment]
I've added an example https://github.com/bernardladenthin/BitcoinAddressFinder/commit/f27da7ac97a0eb8347ca53539660a6c380b7934e

**Comment by bernardladenthin** [comment]
Please try to use the quickstart https://github.com/bernardladenthin/BitcoinAddressFinder#quickstart and use the files
* https://github.com/bernardladenthin/BitcoinAddressFinder/blob/main/examples/config_LMDBToAddressFile.js
* https://github.com/bernardladenthin/BitcoinAddressFinder/blob/main/examples/run_LMDBToAddressFile.bat

**Comment by Noname400** [comment]
thank you so much

**Comment by xCalipsox** [comment]
thank you. everything worked out.
