### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Noname400** [bernardladenthin/BitcoinAddressFinder#12]
Do not plan to implement bip39 (bip 32 bip044)
I did it in python.  But it's very slow

**Comment by Noname400** [comment]
Your program is great, it needs to be continued.

**Comment by bernardladenthin** [comment]
You mean to scan/attack https://en.bitcoin.it/wiki/Seed_phrase ?

**Comment by Noname400** [comment]
Yes
https://iancoleman.io/bip39/

**Comment by Noname400** [comment]
My code
https://github.com/Noname400/Hunt-to-Mnemonic
