### ISSUE TITLE
Invalid maximum heap size: -Xmx16G

### ISSUE THREAD

**Issue by naBBolethano** [bernardladenthin/BitcoinAddressFinder#15]
Invalid maximum heap size: -Xmx16G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

---------------------------------

I am running win 10 + java 8 | Ryzen 5 3600 + 32gb ram & 1080ti 11gb . Any idea on what I am done wrong? thanks

**Comment by bernardladenthin** [comment]
Hi, please use a 64 bit JVM, it seems you are using a 32 bit JVM.
https://stackoverflow.com/questions/62386842/invalid-maximum-heap-size
