### ISSUE TITLE
I ask for your help

### ISSUE THREAD

**Issue by Noname400** [bernardladenthin/BitcoinAddressFinder#17]
Good afternoon, I really need help and I hope you will direct me on the right path.
please tell me which of the files can be used in your project to work through opencl on python.
I just started studying GPU, and of course there are a lot of questions, but if you send me, I will try to solve all the problems myself.
Unfortunately, my hobby is hard to combine with my work. so there is not much time to read the documentation. I mostly learn on the go. using or changing the code. it gives me learning and time savings.
I'm running my project, but I've run into a speed limit.
1. I really want to learn GPU hashing (US256)
2. create hash160 from the private key on the GPU.
my knowledge of c++ is limited.

Can you help and guide me?

**Comment by bernardladenthin** [comment]
Hi, sorry for the late reply. My question on stackoverflow may help?: https://stackoverflow.com/questions/64864778/generate-a-public-key-from-a-private-key-with-opencl-for-secp256k1
