### ISSUE TITLE
plz add example with Key range

### ISSUE THREAD

**Issue by plaber** [bernardladenthin/BitcoinAddressFinder#30]
and also what CPU did you use for rich 2000k/s on rtx2060?

**Comment by bernardladenthin** [comment]
Hi. it was a AMD Ryzen 9 3950x or Intel Core i7-6700K.

**Comment by plaber** [comment]
so if you have AMD Ryzen 9 3950x now, can you test it with disabled 8 cores, does it drop performance or maybe 8 or even 4 cores is enough? i want to buy another cpu just for your script, lol. And for information, i made tests on xeon e5 2690 (14 cores) with dual ddr4 32gb, it rich 850k/s,when my 9400f rich 1060k/s (at 40m keys database both). Sorry if i annoy you.

**Comment by plaber** [comment]
do i need to edit something in config_Find_1OpenCLDevice.js for 14 cores?
maybe
line 11: "threads" : 8,
or
line 26: "maxResultReaderThreads" : 4,

**Comment by plaber** [comment]
so, i changed
 line 11: "threads" : 8,
to
line 11: "threads" : 24,

now i have [2390 k keys/second], and cuda load for 95%, i am happy, thaks

**Comment by bernardladenthin** [comment]
Thanks for feedback. The next release might support more on GPU.
