### ISSUE TITLE
Scanning of other altcoins except Bitcoin

### ISSUE THREAD

**Issue by Musashih** [bernardladenthin/BitcoinAddressFinder#31]
Hello, the description states - a free high-performance tool for quickly scanning random private keys of Bitcoin, Bitcoin Cashu, Bitcoin SV, Litecoin, Dogecoin, Dash, Zcash (and many others) and searching for addresses with a balance.
The main goal is to generate addresses (Bitcoin/altcoin) as quickly as possible using JVM in combination with OpenCL, and check if the address (RIPEMD160 hash) has been used before. This includes possible hash collisions. And how to scan the rest of the altcoins, except bitcoin? It works with Bitcoin, but I didn't recognize the addresses of the ether, I didn't try to talk about the rest of the altos if it happened with ether...

**Comment by bernardladenthin** [comment]
Hi,
address (RIPEMD160 hash) which means secp256k1 ecc keys are supported only. Ether (ethereum) is completely different and has nothing to do with this project.
