### ISSUE TITLE
Could not create Java Virtual maschine

### ISSUE THREAD

**Issue by aszux** [bernardladenthin/BitcoinAddressFinder#32]
Hello;
i extracted/copied all doczuments in the folder by opening run_Find_1OpenCLDevice.bat it stops and in the log are this:

Unrecognized option: --add-opens
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

i tried switching the datas and so on but nothing works.

kindly regards

**Comment by bernardladenthin** [comment]
Hi, I assume you are using a different java vm. Are you using Oracle?

**Comment by aszux** [comment]
Hello, yeah i had the wrong java version. 
Now the bat data are open and need much cpu capacy but looks like it dont do anything. Do it just need time?

(sry for late response i hadnt time)
