### ISSUE TITLE
Feature wish: Incomplete Seed-Phrase as Private Key provider.

### ISSUE THREAD

**Issue by mirasu** [bernardladenthin/BitcoinAddressFinder#38]
Hello, I wonder if this software works to search for deleted seed words? Come on, I have a seed phrase that doesn't work and I have doubts about some words, I would like to look for combinations.
Can that be done with this software or do you know of any?

**Comment by bernardladenthin** [comment]
Hi, in general, it is possible to implement. I'm working on some refactorings to implement features like these.

**Comment by bernardladenthin** [comment]
I've added the idea of setting a key range to future improvements.
