### ISSUE TITLE
Launching on Cuda

### ISSUE THREAD

**Issue by baruka99-lab** [bernardladenthin/BitcoinAddressFinder#40]
Hi! After launching the program via run_1OpenCLDevice, the program generates 96k keys/second. The video card is not involved in the processes. Nvidia RTX 3050 Laptop graphics card, Cuda 12 is installed. Intel has disabled the second graphics card. Maybe additional settings are required?

**Comment by bernardladenthin** [comment]
Hi, can you have a look in the Windows TaskManager into GPU and open the CUDA graph? Do you see some load there? Maybe your CPU is very slow. I`m already working on a lot of improvements to use the GPU only. Greetings, Bernard

**Comment by baruka99-lab** [comment]
gpu cuda is not displayed for some reason
![image](https://github.com/bernardladenthin/BitcoinAddressFinder/assets/157349448/7485c015-215e-42f6-bedd-89a47382ce5d)

**Comment by bernardladenthin** [comment]
On the left side, you need to open the performance overview in the menu bar with the charts inside the task manager.

**Comment by baruka99-lab** [comment]
![image](https://github.com/bernardladenthin/BitcoinAddressFinder/assets/157349448/3e2f7237-0b45-49db-9a40-15076152fb4d)

**Comment by bernardladenthin** [comment]
You are using too less RAM. Please also use a drop down of the GPU window (e. G. 3D or copy and select CUDA)

**Comment by baruka99-lab** [comment]
Sorry to waste your time. But I didn't understand anything, what should I do?

**Comment by baruka99-lab** [comment]
![image](https://github.com/bernardladenthin/BitcoinAddressFinder/assets/157349448/2e1bb348-ef21-4cfb-8572-5b4e9b887406)

**Comment by bernardladenthin** [comment]
Yes, CUDA is operational. However, your RAM is insufficient to keep the LMDB fully in memory. As a result, your SSD is performing swapping operations, leading to the high load on the SSD.

**Comment by baruka99-lab** [comment]
How much RAM do you recommend?

**Comment by bernardladenthin** [comment]
It depends on the database. For the light database, I recommend 16GB. For the full database, you need a minimum of 64GB.

**Comment by baruka99-lab** [comment]
OK. Thanks. Have a nice day!
