### ISSUE TITLE
WARN : Attention, queue is full. Please increase queue size.

### ISSUE THREAD

**Issue by mrkariimi** [bernardladenthin/BitcoinAddressFinder#42]
hello dear sir
I hope you are well
i am use linux ubuntu 20.04 (cpu : Ryzen 9 3950X with 16 core and 32 threads , ram : 128GB , gpu :Radeon RX 6900 XT)
What has happened ?
Should I increase the queue?
If I stop the program and start again, the keys are checked from the beginning. Is that the keys are selected randomly or by sequence?
If for any reason my computer restarts and the program runs from the beginning, is this good or bad?

could you please discribe that i have 4 thread but way thread 1 is used ?
and please discribe pool .

![queue](https://github.com/bernardladenthin/BitcoinAddressFinder/assets/118912171/baf6b190-910c-42be-8a0c-49c6d45b7f62)

my effective is : ~830k keys/s

![linux](https://github.com/bernardladenthin/BitcoinAddressFinder/assets/118912171/8017b448-6b1a-46c3-a902-aa966880b62e)

**Comment by mrkariimi** [comment]
could you please discribe that i have 4 thread but way thread 1 is used ?
and please discribe pool.

**Comment by bernardladenthin** [comment]
Upon restarting, secure random is used again, generating highly random keys each time. "Queue is full" indicates that your CPU is too slow to check the keys in the LMDB database, and the OpenCL is faster than your CPU can handle this key production. This issue will be addressed in a future release by utilizing the GPU more for hashing.

**Comment by mrkariimi** [comment]
When is the next release of the software?

**Comment by bernardladenthin** [comment]
I'll create a new release now. Then, you'll be able to test and use the new configuration format.

**Comment by bernardladenthin** [comment]
Just for you, a new release, happy finding: https://github.com/bernardladenthin/BitcoinAddressFinder/releases/tag/1.3.0-SNAPSHOT

**Comment by mrkariimi** [comment]
thank you it works i achive 3940 k key/ps
power consumption ~ 400 w
