### ISSUE TITLE
need a bit help?

### ISSUE THREAD

**Issue by dextronomous** [bernardladenthin/BitcoinAddressFinder#7]
hi there, really love the software, i am not a full programmer so came across some difficulties, like, 
need maven for apache, need java developer environment added to path btw, both, needed to change a version number inside the pom.xml file for :<groupId>net.ladenthin</groupId><artifactId>javacommons</artifactId><version>1.2.0</version> to <version>1.1.0</version> otherwise the compilation did not went trough, when i start one of the example batch files you have in the folders, i've also put the lmdb folder in there, it started,

java -server -Xms512M -Xmx16G -Dlogback.configurationFile=logbackConfiguration.xml -jar bitcoinaddressfinder-1.0.0-SNAPSHOT-jar-with-dependencies.jar config_Find_1OpenCLDevice.js  1>>log_Find_1OpenCLDevice.txt 2>&1
is it here using gpu? or not? thanks so much again, 
in the *.txt file it says Exception in thread "main" org.lmdbjava.LmdbNativeException$ConstantDerivedException: Platform constant error code: ESRCH No such process (3) , this is just to ask if it is important, 
20:25:06,437 till 22:26:33,442 it scanned the db, is that ok, now my question, is there a print on screen method, cause it does stay still over there, or should i close this one and start the other one, run_Find_1OpenCLDeviceAnd2CPUProducer

2021-05-29 22:54:03,500 [Timer-0] INFO  net.ladenthin.bitcoinaddressfinder.ConsumerJava - Statistics: [Checked 0 M keys in 27 minutes] [0 k keys/second] [0 M keys/minute] [Times an empty consumer: 17630] [Average contains time: 19 ms] [keys queue size: 4] [Hits: 0] , gpu is not used it show in app, and cpu is a little bit used, but almost all my ram is gone,

**Comment by dextronomous** [comment]
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/BitcoinAddressFinder-main/src/main/java/net/ladenthin/bitcoinaddressfinder/ByteBufferUtility.java:[23,16] cannot find symbol
  symbol:   class Cleaner
  location: package sun.misc
[ERROR] /D:/BitcoinAddressFinder-main/src/main/java/net/ladenthin/bitcoinaddressfinder/ByteBufferUtility.java:[45,9] cannot find symbol
  symbol:   class Cleaner
  location: class net.ladenthin.bitcoinaddressfinder.ByteBufferUtility
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.669 s
[INFO] Finished at: 2021-05-30T01:16:11+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project bitcoinaddressfinder: Compilation failure: Compilation failure:
[ERROR] /D:/BitcoinAddressFinder-main/src/main/java/net/ladenthin/bitcoinaddressfinder/ByteBufferUtility.java:[23,16] cannot find symbol
[ERROR]   symbol:   class Cleaner
[ERROR]   location: package sun.misc
[ERROR] /D:/BitcoinAddressFinder-main/src/main/java/net/ladenthin/bitcoinaddressfinder/ByteBufferUtility.java:[45,9] cannot find symbol
[ERROR]   symbol:   class Cleaner
[ERROR]   location: class net.ladenthin.bitcoinaddressfinder.ByteBufferUtility
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Press any key to continue . . .
compiling gave this

**Comment by bernardladenthin** [comment]
Hi,
I'll try to help you soon. First of all you can get a precompiled version here: https://github.com/bernardladenthin/BitcoinAddressFinder/releases

Are you using Linux? Maybe lmdb must be configured different for your LMDB exception. I've tested under Windows only.

**Comment by dextronomous** [comment]
Hi,
I now am getting this one with compiling, [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException,

the compiled version you mean the jar file, and the bat files, ok hope got this one right. ok so i am using windows10, work no more, 
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @5f8edcc5

this one is since my first post i could not make the log file say anything else anymore, but got maven 3.81. java dk 16.0.1 good or bad please help, thanks a lot for you'r advice.

**Comment by bernardladenthin** [comment]
Statistics: [Checked 5 M keys in 427 minutes] is the absolute statistics. It runs.
[0 k keys/second] [0 M keys/minute] is correct, you are slower than 0k keys/s and 0 M keys/minute.

[Times an empty consumer: 671] [Average contains time: 35 ms] is good and indicates the LMDB is fast enough to check the database.

Your current "issue" is a too slow private / public key pair generation.

Now your next step should be to remove the javaProducer and add only one OpenCL producer. Than lets see what happens. Maybe the OpenCL device is not configured properly or the OpenCL Code is not compatible.

I've tested with nVidia only currently.

**Comment by dextronomous** [comment]
ok i got an nvidia card to, 1660ti, how to get a bit more verbose details, what it is doing currently, or progress, is that possible?
thanks you a lot for your help,

**Comment by bernardladenthin** [comment]
In the config section producerOpenCL, please try to reduce gridNumBits to something like 16 or lesser. It might be possible that your GPU can't allocate so much memory for 18 bits parallel at once.

**Comment by dextronomous** [comment]
thank you a lot man, will do some running a while, see in the morning, where as will results be? thanks

**Comment by bernardladenthin** [comment]
You can simply do a test run if you enforce the creation of an private key wheras the public key is in your databse. My databases contains the well known puzzle transaction. This means you can change "privateKeyMaxNumBits" : 256 to something lesser e. g. 20. Then you'll see a lot of hits in the log. You can also add the option logSecretBase to true in a consumer to get some more informations about the used key ranges.

I suggest to do some dry runs with activated "runtimePublicKeyCalculationCheck". This will compare OpenCL created public keys with CPU (Java) created keys to have a built in test that your OpenCL device works properly.

**Comment by dextronomous** [comment]
hi bernard, thanks man again, i have loads of matches, now if i want to see a change if possible, like addresses, of the keys, etc. no balances right now, or own list of add's to check compare with? how to start that, thanks
