### ISSUE TITLE
Read from text file

### ISSUE THREAD

**Issue by Toddtroy** [bernardladenthin/BitcoinAddressFinder#9]
Read millions of private keys from text file similar to brainwallet except you dont have to take sha256 hash the hash is pregenerated just do the conversion to compressed and uncompressed addresses and private keys save the converted result to text file this can also include pattern matching if need be since we dont want to save millions of those this can also have flags if you want to all the results -s or the results whose pattern matches to the pattern or address you input -sp.

**Comment by bernardladenthin** [comment]
Hi,
it's more or less the same as #3 .
Yes, I take your request to support pre generated sha256 files to create and check key pairs including pattern matching.

Thanks in advance and many regards, Bernard

**Comment by bernardladenthin** [comment]
It's implemented. For example, refer to: https://github.com/bernardladenthin/BitcoinAddressFinder/blob/ad9f09343659a75c4444480225be63a091f4fc00/examples/config_Find_SecretsFile.js. The mode for pre-hashed SHA256 values is set to "SHA256".
